apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: chatbot-jan20-1
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/maysunfaisal/chatbot-jan20-1:68d96feb26a569f0f3293f67dee468fcb77ed371@sha256:69b7092f858bc2a65e2b1b168b27c363be7fe9c7ddca492022917ee48bc9c922 # use pre-built to bootstrap 
          name: app-inference
